import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav className="sticky top-0 z-50 border-b border-zinc-200 bg-white/80 backdrop-blur">
          <div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4">
            <Link href="/" className="text-xl font-bold">
              MySite
            </Link>

            <div className="flex gap-6 text-sm font-medium">
              <Link href="/" className="hover:text-blue-600">
                Board
              </Link>

              <Link href="/notes/1" className="hover:text-blue-600">
                Project Ideas
              </Link>

              <Link href="/notes/2" className="hover:text-blue-600">
                To-Do
              </Link>

              <Link href="/notes/3" className="hover:text-blue-600">
                Resources
              </Link>
            </div>
          </div>
        </nav>

        {children}
      </body>
    </html>
  );
}